language: go
go:
  - "1.9"
  - "1.10"
before_install:
  - go get github.com/mattn/goveralls
install:
  - make dependencies
script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci
notifications:
  slack:
    rooms:
      secure: "e+nU19BZBV6S6sOTTh0aEbkwCz6/FQ/ijErTam/c2fQym062j5P8tajbSB/D7O1PEzLeIfijIkhG4z9axk6g7LhWcflWFkkVhfMoPp5QGRlKwL+5+oCN2e7OGfTVOMETd+0RnE0aFMmicNUQPEAu1Xclh1My9G6MuQ5SngORebEO3KuPRXblEfSIJ4vWF7GHpwWPvCknx5o2d8UhvJE1PnwncSZ4WgIucv5Cre8icp/WcwGi3kbOV3XQduLPQMjGR1nvw3ViVnVMy3OnxWQc17snSHkjaSJUNKppT77Z+sopt0V588hWnuL4FHlss1pRxc9qsOC0y5yAS47UpxWlPr2Bu6lZZKyRs22has6cTGSvMM3cnGe30iRzFPb7vVCEIaf4PX9UsRelhTud/NA5fyP0KKDMXAOteeSyloP0QrjqcOTUnRs27bViLnlLdxZ1txd48U9mRg3Lo1m8gvumGTdNVs1KMVLlu4kCxPppiIfnvoiewxtL2uynghqei06i5jExofE4KNT8Njx8JHpeDVZc4V3pVkYEZrThf2/ANeBW1YF7RtJjIX1uzLMC2KVwq+gijzdPwHN1+FVqAmpbwoeIbW8B/DfE+je6hB9zL29jlo87w/3hZElIA9ub4JLNHfNbymtE+h4CcAwTaBBgj3b+VyYGeTNsNLOm4xOASoE="
    on_success: always
    on_failure: always

